import { isSkillId, type SkillId } from "../skills/types.js";

export type ItemRarity =
  | "COMMON"
  | "UNCOMMON"
  | "RARE"
  | "EPIC"
  | "LEGENDARY";

export const ITEM_RARITIES: readonly ItemRarity[] = [
  "COMMON",
  "UNCOMMON",
  "RARE",
  "EPIC",
  "LEGENDARY",
] as const;

export type EquipmentSlot =
  | "main_hand"
  | "off_hand"
  | "helmet"
  | "chest"
  | "gloves"
  | "belt"
  | "boots"
  | "necklace"
  | "ring"
  | "cape"
  | "artifact";

export const EQUIPMENT_SLOTS: readonly EquipmentSlot[] = [
  "main_hand",
  "off_hand",
  "helmet",
  "chest",
  "gloves",
  "belt",
  "boots",
  "necklace",
  "ring",
  "cape",
  "artifact",
] as const;

export type LegacyItemSlot = "weapon" | "offhand" | "WEAPON" | "ARMOR" | "CAPE" | "AMULET" | "RING";

export type EquipmentStats = {
  hp?: number;
  attack?: number;
  defense?: number;
  power?: number;
};

export type ResolvedEquipmentStats = {
  hp: number;
  attack: number;
  defense: number;
  power: number;
};

export type ItemId = string;

export type EquipmentAffix = {
  affixId: string;
  stat: keyof EquipmentStats;
  value: number;
};

export type EquipmentInstance = {
  affixes: EquipmentAffix[];
  baseItemId: string;
  instanceId: string;
  ilvl: number;
  rarity: ItemRarity;
  rolledStats: EquipmentStats;
  setId?: string;
  /**
   * Rings generated by the MVP path always carry a SkillId. `null` is reserved
   * for reviving legacy saves whose rings predate ring-backed skills.
   */
  skillId?: SkillId | null;
  slot: EquipmentSlot;
  upgradeLevel: number;
};

export type EquipmentItem = EquipmentInstance & {
  id: ItemId;
  kind?: "equipment";
  name: string;

  stats: EquipmentStats;
  baseStats?: EquipmentStats;

  itemLevel?: number;
  value?: number;
};

export type NonEquipmentItem = {
  id: ItemId;
  kind: "material" | "resource" | "consumable" | "misc" | "special" | "quest";
  name: string;
  quantity?: number;
  quality?: number;
  value?: number;
};

export type Item = EquipmentItem | NonEquipmentItem;

const LEGACY_ITEM_SLOT_MAP: Partial<Record<LegacyItemSlot, EquipmentSlot>> = {
  weapon: "main_hand",
  offhand: "off_hand",
  WEAPON: "main_hand",
  ARMOR: "chest",
  CAPE: "cape",
  AMULET: "necklace",
  RING: "ring",
};

export function isEquipmentSlot(slot: unknown): slot is EquipmentSlot {
  return typeof slot === "string" && (EQUIPMENT_SLOTS as readonly string[]).includes(slot);
}

export function isItemRarity(rarity: unknown): rarity is ItemRarity {
  return typeof rarity === "string" && (ITEM_RARITIES as readonly string[]).includes(rarity);
}

export function normalizeEquipmentSlot(slot: unknown): EquipmentSlot | null {
  if (isEquipmentSlot(slot)) return slot;
  if (typeof slot !== "string") return null;
  return LEGACY_ITEM_SLOT_MAP[slot as LegacyItemSlot] ?? null;
}

function normalizeUpgradeLevel(value: unknown): number {
  if (typeof value !== "number" || !Number.isFinite(value)) return 0;
  return Math.max(0, Math.floor(value));
}

function normalizeIlvl(candidate: Partial<EquipmentItem>): number {
  const value = candidate.ilvl ?? candidate.itemLevel;
  if (typeof value !== "number" || !Number.isFinite(value)) return 1;
  return Math.max(1, Math.min(1000, Math.floor(value)));
}

function normalizeAffixes(value: unknown): EquipmentAffix[] {
  if (!Array.isArray(value)) return [];
  return value.flatMap((affix): EquipmentAffix[] => {
    if (!affix || typeof affix !== "object") return [];
    const candidate = affix as Partial<EquipmentAffix>;
    if (
      typeof candidate.affixId !== "string" ||
      typeof candidate.stat !== "string" ||
      typeof candidate.value !== "number" ||
      !Number.isFinite(candidate.value)
    ) {
      return [];
    }
    return [{ affixId: candidate.affixId, stat: candidate.stat as keyof EquipmentStats, value: candidate.value }];
  });
}

export function isEquipmentItem(item: unknown): item is EquipmentItem {
  if (!item || typeof item !== "object") return false;
  const candidate = item as Partial<EquipmentItem>;
  return typeof candidate.id === "string" && typeof candidate.name === "string" && isEquipmentSlot(candidate.slot);
}

export function normalizeEquipmentItem(item: unknown): EquipmentItem | null {
  if (!item || typeof item !== "object") return null;

  const candidate = item as Partial<EquipmentItem> & { slot?: unknown };
  const slot = normalizeEquipmentSlot(candidate.slot);
  if (!slot || typeof candidate.id !== "string" || typeof candidate.name !== "string") return null;
  if (candidate.rarity !== undefined && !isItemRarity(candidate.rarity)) return null;
  const stats = candidate.stats ?? {};
  const ilvl = normalizeIlvl(candidate);
  const skillId = slot === "ring"
    ? candidate.skillId == null
      ? null
      : isSkillId(candidate.skillId)
        ? candidate.skillId
        : null
    : undefined;
  if (slot === "ring" && candidate.skillId != null && skillId === null) return null;

  return {
    ...candidate,
    affixes: normalizeAffixes(candidate.affixes),
    baseItemId: typeof candidate.baseItemId === "string" ? candidate.baseItemId : candidate.id,
    id: candidate.id,
    ilvl,
    instanceId: typeof candidate.instanceId === "string" ? candidate.instanceId : candidate.id,
    itemLevel: candidate.itemLevel ?? ilvl,
    kind: "equipment",
    name: candidate.name,
    rolledStats: candidate.rolledStats ?? stats,
    skillId,
    slot,
    stats,
    baseStats: candidate.baseStats ?? stats,
    rarity: isItemRarity(candidate.rarity) ? candidate.rarity : "COMMON",
    upgradeLevel: normalizeUpgradeLevel(candidate.upgradeLevel),
  };
}
